### ISSUE TITLE
JSON format end_time

### ISSUE THREAD

**Issue by j-woz** [ECP-CANDLE/Database#2]
This seems to be in an unnecessary structure, unlike start_time: is this intentional?

[
    {
        "status": "Started",
        "start_time": "2017-07-02 20:53:07.676214",

...

    {
        "status": {
            "set": "Finished"
        },
        "date_modified": {
            "set": "NOW"
        },
        "end_time": {
            "set": "2017-07-02 21:53:59.900428"
        },

**Comment by hyoo** [comment]
this meant to be solr atomic update format.
https://cwiki.apache.org/confluence/display/solr/Updating+Parts+of+Documents

**Comment by j-woz** [comment]
Got it.
